version: '3.8'

services:

  nature-reserve-map:
    container_name: nature-reserve-map
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      - proxy
    expose:
      - "80"
    ports:
      - '1337:80'
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VIRTUAL_HOST=www.julianschroeter.rocks, julianschroeter.rocks
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=www.julianschroeter.rocks, julianschroeter.rocks
      - LETSENCRYPT_EMAIL=geschroeteter@gmail.com
networks:
  proxy:
    external:
      name: nginx-proxy
