version: '3.8'

services:

  julianschroeter-public:
    container_name: nature-reserve-map
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    networks:
      - proxy
    expose:
      - "80"
    ports:
      - '1337:80'
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VIRTUAL_HOST=www.julianschroeter.de, www.julianschroeter.com, julianschroeter.de, julianschroeter.com
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=www.julianschroeter.de, www.julianschroeter.com, julianschroeter.de, julianschroeter.com
      - LETSENCRYPT_EMAIL=geschroeteter@gmail.coom
networks:
  proxy:
    external:
      name: nginx-proxy